model_tuning:
    optimizer:
        - "sgd"
        - "adam"
        - "adagrad"
    epochs: 
        - 30
    batch_size:
        - 8
        - 16
    scoring: "accuracy"

model_production:
    optimizer: "adam"
    epochs: 60
    batch_size: 16
            